const data = {
  events: [
    {
      name: 'La 7ème édition de Tunisia Digital Summit',
      slug: 'La 7ème édition de Tunisia Digital Summit',
      where: 'Tunis /theThingsLand',
      categories: ['category1', 'category3'],
      types: ['competition', 'presentation', 'workshops'],
      owner: 'someone',
      target: 'Anyone',
      price: 'Free Entry',
      start_d: 26,
      end_d: 28,
      start_m: 'June',
      end_m: 'June',
      time: '08:30 AM',
      year: 2023,

      image:
        'https://scontent.ftun10-1.fna.fbcdn.net/v/t39.30808-6/352180837_662498392378028_6268851799442282251_n.jpg?stp=dst-jpg_s960x960&_nc_cat=107&ccb=1-7&_nc_sid=340051&_nc_ohc=JfAggZzmkXEAX976xKG&_nc_ht=scontent.ftun10-1.fna&oh=00_AfDYtVtdY62dBTLZHz1JCBwxxo9AGUFemoy-WanURHIg_Q&oe=6490D180',
    },
    {
      name: 'ISGIS ROBOTS V2.0',
      slug: 'ISGIS ROBOTS V2.0',
      where: 'Sfax /Institut Supérieur de Gestion Industrielle - ISGI',
      categories: ['Technologie', 'Science/Education'],
      types: ['presentation', 'workshops'],
      owner: 'Club robotique ISGI sfax',
      target: 'Anyone',
      price: 'Free Entry',
      start_d: 29,
      end_d: 29,
      start_m: 'October',
      end_m: 'October',
      time: '08:30 AM',
      year: 2023,

      image:
        'https://scontent.ftun9-1.fna.fbcdn.net/v/t39.30808-6/351345147_215591367954895_4461765145874775302_n.jpg?stp=dst-jpg_s960x960&_nc_cat=100&ccb=1-7&_nc_sid=340051&_nc_ohc=c4dwrdTwa70AX8cDZT9&_nc_ht=scontent.ftun9-1.fna&oh=00_AfBQIkt1GtQJcICYcGZmvieX8hsurl_u7GJ0iZSw3tKzYA&oe=649090D0',
    },
    {
      name: 'AI4Good Summer Incubator',
      slug: 'AI4Good Summer Incubator',
      where: 'Online event',
      categories: ['Entrepreneurship', 'Science/Education'],
      types: ['competition', 'workshops'],
      owner: 'Teens in AI',
      target: 'Anyone',
      price: 'Free Entry',
      start_d: 24,
      end_d: 24,
      start_m: 'Jul',
      end_m: 'Jul',
      time: '08:30 AM',
      year: 2023,

      image:
        'https://scontent.ftun9-1.fna.fbcdn.net/v/t39.30808-6/344584757_902523014377891_1966468191493688448_n.jpg?stp=dst-jpg_s960x960&_nc_cat=110&ccb=1-7&_nc_sid=340051&_nc_ohc=WlhtdT-3p6AAX-sNheG&_nc_ht=scontent.ftun9-1.fna&oh=00_AfC-9wPn3xLQuGvwSCa0Nd7Rm6oHiL_A-tbPP-IxGo3QMQ&oe=6492771F',
    },
    {
      name: 'THIS IS n°2',
      slug: 'ev2-name',
      where: 'Sousse /theThingsLand',
      categories: ['category1', 'category2', 'Entrepreneurship'],
      types: ['workshops'],
      owner: 'an other one',
      target: 'Anyone',
      price: 'Free Entry',
      start_d: 26,
      end_d: 28,
      start_m: 'June',
      end_m: 'July',
      year: 2023,

      //image: '/images/p2.jpg',
    },
    {
      name: 'THIS IS n°3',
      slug: 'ev3-name',
      where: 'Meri5 /theThingsLand',
      categories: ['category1', 'category2'],
      types: ['competition', 'presentation', 'workshops'],
      owner: 'an other one',
      target: 'Anyone',
      price: 'Free Entry',
      start_d: 26,
      end_d: 26,
      start_m: 'June',
      end_m: 'July',
      year: 2023,

      //image: '/images/p3.jpg',
    },
    {
      name: 'THIS IS n°4',
      slug: 'ev4-name',
      where: 'Meri5 /theThingsLand',
      categories: ['category1', 'category2'],
      types: ['competition', 'presentation', 'workshops'],
      owner: 'an other one',
      target: 'Anyone',
      price: 'Free Entry',

      //image: '/images/p3.jpg',
    },
    {
      name: 'THIS IS n°5',
      slug: 'ev5-name',
      where: 'Meri5/theThingsLand',
      categories: ['category1', 'category2'],
      types: [],
      owner: 'an other one',
      target: 'Anyone',
      price: 'Free Entry',

      //image: '/images/p3.jpg',
    },
    {
      name: 'THIS IS n°6',
      slug: 'ev6-name',
      where: 'Meri5/theThingsLand',
      categories: ['category1', 'category2'],
      types: ['competition', 'presentation', 'workshops'],
      owner: 'an other one',
      target: 'Anyone',
      price: 'Free Entry',

      //image: '/images/p3.jpg',
    },
  ],
};

export default data;
